version: "3.2"
services:
  sgicpc-official-website:
    container_name: sgicpc-official-website
    image: sgicpc-official-website
    restart: always
    volumes: 
      - "/web/sgicpc-official-website:/web/sgicpc-official-website"
    ports:
      - "4444:4444"
